### ISSUE TITLE
Please take this down

### ISSUE THREAD

**Issue by NyaomiDEV** [Randymations/Glasscord-Installer#4]
In an effort to bury any and all evidence that this mod ever existed, I am asking you to cease this repository and desist from ever uploading any part of my mod, be it as final bundled release or as source code. (Referring specifically to your last released ZIP file)

Sure you can just dismiss me, but I am really trying to get my sanity back here.

**Comment by Randymations** [comment]
I respect your work and will remove your binary if you ultimately insist. I understand how this has affected you and would like to ask if you'd be open to me keeping it up but removing all references to you. If not, I'll remove it immediately.

**Comment by NyaomiDEV** [comment]
I feel like there is work that is already out there as a de facto replacement for the project I did. Take a look at uwu/Acrylic.

I do insist because I do not want to be associated with Glasscord anymore, for personal reasons.

**Comment by Randymations** [comment]
I had no idea that project existed, thank you for informing me! I'll remove your binary immediately.
